### ISSUE TITLE
Error message at plugin install

### ISSUE THREAD

**Issue by bugsysop** [afragen/git-updater-gitea#4]
When installing the Gitea Addon, WP generate this huge Warning

`Warning: Cannot modify header information - headers already sent by (output started at /Users/myself/Local Sites/publication/app/public/wp-includes/functions.php:5279) in /Users/myself/Local Sites/publication/app/public/wp-includes/pluggable.php on line 1416`

After in fact all work fine...

Configuration:

* Environment: Local
* Wordpress: 6.1
* PHP version: 7.4.1
* Git Updater: 11.1.9
* Web server: Nginx

Note: this was also the case with WP version 6.0.* and previous version of Git Updater & Gitea plugin

**Comment by afragen** [comment]
And you installed the Gitea API add-on from the Add-On tab?

**Comment by afragen** [comment]
I just created a fresh installation WP 6.1, PHP 7.4.30, nginx, Git Updater 11.1.9. I went to the Add-On tab and clicked the Gitea API Add-on `Install and Activate` button. 

Additional plugin installed and no errors presented.

Can you think of any other way to reproduce? FWIW I'm using LocalWP.

**Comment by bugsysop** [comment]
Yes Installed from the Tab!
I also use LocalWP

Will investigate now for an incompatibility with another plugin...
Thanks for your prompt reaction.

**Comment by bugsysop** [comment]
Debug install with same configuration but no other plugins active. 
I have still the error message.

Occure after translation upgrade... Maybe nothing to do with the problem

![Screenshot-2022-11-02-at-22-47-27-https __debug local](https://user-images.githubusercontent.com/365281/199609284-5ce45064-923b-4b8e-b21f-cf87df151e47.png)

Git Updater is installed from the Github .zip package.
Git Updater Gitea from the plugin add-on tab.

**Comment by bugsysop** [comment]
My version of LocalWP is 6.4.3+6116

**Comment by bugsysop** [comment]
PHP Logs

`[02-Nov-2022 21:41:31 UTC] PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php:784
Stack trace:
#0 /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php(872): load_textdomain('default', '/Users/aris/Loc...', 'fr_FR')
#1 /Users/aris/Local Sites/debug/app/public/wp-includes/class-wp-fatal-error-handler.php(47): load_default_textdomain()
#2 [internal function]: WP_Fatal_Error_Handler->handle()
#3 {main}
  thrown in /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php on line 784
[02-Nov-2022 21:42:17 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wp_cache_get() in /Users/aris/Local Sites/debug/app/public/wp-includes/option.php:165
Stack trace:
#0 /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php(63): get_option('WPLANG')
#1 /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php(139): get_locale()
#2 /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php(766): determine_locale()
#3 /Users/aris/Local Sites/debug/app/public/wp-includes/load.php(1395): load_textdomain('default', '/Users/aris/Loc...')
#4 /Users/aris/Local Sites/debug/app/public/wp-includes/class-wpdb.php(1815): wp_load_translations_early()
#5 /Users/aris/Local Sites/debug/app/public/wp-includes/class-wpdb.php(734): wpdb->db_connect()
#6 /Users/aris/Local Sites/debug/app/public/wp-includes/load.php(562): wpdb->__construct('root', 'root', 'local', 'localhost')
#7 /Users/aris/Local Sites/debug/app/public/wp-settings.php(124): require_wp_db()
#8 phar:///Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cl in /Users/aris/Local Sites/debug/app/public/wp-includes/option.php on line 165
[02-Nov-2022 21:42:17 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function wp_cache_get() in /Users/aris/Local Sites/debug/app/public/wp-includes/option.php:165
Stack trace:
#0 /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php(63): get_option('WPLANG')
#1 /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php(139): get_locale()
#2 /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php(766): determine_locale()
#3 /Users/aris/Local Sites/debug/app/public/wp-includes/load.php(1395): load_textdomain('default', '/Users/aris/Loc...')
#4 /Users/aris/Local Sites/debug/app/public/wp-includes/class-wpdb.php(1815): wp_load_translations_early()
#5 /Users/aris/Local Sites/debug/app/public/wp-includes/class-wpdb.php(734): wpdb->db_connect()
#6 /Users/aris/Local Sites/debug/app/public/wp-includes/load.php(562): wpdb->__construct('root', 'root', 'local', 'localhost')
#7 /Users/aris/Local Sites/debug/app/public/wp-settings.php(124): require_wp_db()
#8 phar:///Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/wp-cl in /Users/aris/Local Sites/debug/app/public/wp-includes/option.php on line 165
[02-Nov-2022 21:42:17 UTC] PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php:784
Stack trace:
#0 /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php(872): load_textdomain('default', '/Users/aris/Loc...', 'fr_FR')
#1 /Users/aris/Local Sites/debug/app/public/wp-includes/class-wp-fatal-error-handler.php(47): load_default_textdomain()
#2 [internal function]: WP_Fatal_Error_Handler->handle()
#3 {main}
  thrown in /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php on line 784
[02-Nov-2022 21:42:17 UTC] PHP Fatal error:  Uncaught Error: Call to a member function set() on null in /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php:784
Stack trace:
#0 /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php(872): load_textdomain('default', '/Users/aris/Loc...', 'fr_FR')
#1 /Users/aris/Local Sites/debug/app/public/wp-includes/class-wp-fatal-error-handler.php(47): load_default_textdomain()
#2 [internal function]: WP_Fatal_Error_Handler->handle()
#3 {main}
  thrown in /Users/aris/Local Sites/debug/app/public/wp-includes/l10n.php on line 784
[02-Nov-2022 21:46:35 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /Users/aris/Local Sites/debug/app/public/wp-includes/functions.php:5279) in /Users/aris/Local Sites/debug/app/public/wp-includes/pluggable.php on line 1416
[02-Nov-2022 21:46:35 UTC] PHP Stack trace:
[02-Nov-2022 21:46:35 UTC] PHP   1. {main}() /Users/aris/Local Sites/debug/app/public/wp-admin/options.php:0
[02-Nov-2022 21:46:35 UTC] PHP   2. require_once() /Users/aris/Local Sites/debug/app/public/wp-admin/options.php:19
[02-Nov-2022 21:46:35 UTC] PHP   3. do_action() /Users/aris/Local Sites/debug/app/public/wp-admin/admin.php:175
[02-Nov-2022 21:46:35 UTC] PHP   4. WP_Hook->do_action() /Users/aris/Local Sites/debug/app/public/wp-includes/plugin.php:517
[02-Nov-2022 21:46:35 UTC] PHP   5. WP_Hook->apply_filters() /Users/aris/Local Sites/debug/app/public/wp-includes/class-wp-hook.php:332
[02-Nov-2022 21:46:35 UTC] PHP   6. Fragen\Git_Updater\Settings->update_settings() /Users/aris/Local Sites/debug/app/public/wp-includes/class-wp-hook.php:308
[02-Nov-2022 21:46:35 UTC] PHP   7. Fragen\Git_Updater\Settings->redirect_on_save() /Users/aris/Local Sites/debug/app/public/wp-content/plugins/git-updater/src/Git_Updater/Settings.php:694
[02-Nov-2022 21:46:35 UTC] PHP   8. wp_safe_redirect() /Users/aris/Local Sites/debug/app/public/wp-content/plugins/git-updater/src/Git_Updater/Settings.php:784
[02-Nov-2022 21:46:35 UTC] PHP   9. wp_redirect() /Users/aris/Local Sites/debug/app/public/wp-includes/pluggable.php:1524
[02-Nov-2022 21:46:35 UTC] PHP  10. header() /Users/aris/Local Sites/debug/app/public/wp-includes/pluggable.php:1416
[02-Nov-2022 21:46:35 UTC] PHP Warning:  Cannot modify header information - headers already sent by (output started at /Users/aris/Local Sites/debug/app/public/wp-includes/functions.php:5279) in /Users/aris/Local Sites/debug/app/public/wp-includes/pluggable.php on line 1419
[02-Nov-2022 21:46:35 UTC] PHP Stack trace:
[02-Nov-2022 21:46:35 UTC] PHP   1. {main}() /Users/aris/Local Sites/debug/app/public/wp-admin/options.php:0
[02-Nov-2022 21:46:35 UTC] PHP   2. require_once() /Users/aris/Local Sites/debug/app/public/wp-admin/options.php:19
[02-Nov-2022 21:46:35 UTC] PHP   3. do_action() /Users/aris/Local Sites/debug/app/public/wp-admin/admin.php:175
[02-Nov-2022 21:46:35 UTC] PHP   4. WP_Hook->do_action() /Users/aris/Local Sites/debug/app/public/wp-includes/plugin.php:517
[02-Nov-2022 21:46:35 UTC] PHP   5. WP_Hook->apply_filters() /Users/aris/Local Sites/debug/app/public/wp-includes/class-wp-hook.php:332
[02-Nov-2022 21:46:35 UTC] PHP   6. Fragen\Git_Updater\Settings->update_settings() /Users/aris/Local Sites/debug/app/public/wp-includes/class-wp-hook.php:308
[02-Nov-2022 21:46:35 UTC] PHP   7. Fragen\Git_Updater\Settings->redirect_on_save() /Users/aris/Local Sites/debug/app/public/wp-content/plugins/git-updater/src/Git_Updater/Settings.php:694
[02-Nov-2022 21:46:35 UTC] PHP   8. wp_safe_redirect() /Users/aris/Local Sites/debug/app/public/wp-content/plugins/git-updater/src/Git_Updater/Settings.php:784
[02-Nov-2022 21:46:35 UTC] PHP   9. wp_redirect() /Users/aris/Local Sites/debug/app/public/wp-includes/pluggable.php:1524
[02-Nov-2022 21:46:35 UTC] PHP  10. header() /Users/aris/Local Sites/debug/app/public/wp-includes/pluggable.php:1419
`

**Comment by afragen** [comment]
I'm on US English so maybe that's the difference. What translations were updated?

**Comment by afragen** [comment]
> Git Updater is installed from the Github .zip package.

Can you make sure the `wp-content/plugins/git-updater/` and not something else?

**Comment by bugsysop** [comment]
Translation is French (fr_FR)

**Comment by bugsysop** [comment]
Removing all plugins apart Git Updater, and installing the add-on, now without error message...

**Comment by afragen** [comment]
What other plugins were installed?

**Comment by bugsysop** [comment]
Actives
* Bloc Manager (by Darren Cooney)
* Co-Authors Plus
* Code Snippets
* Find My Blocks!
* Git Updater
* Git Updater - Gitea
* Insert Special Characters
* List category posts
* Plugin Dependencies

Inactives
* Better Search Replace
* Custom Post Type Cleanup
* Custom Post Type UI
* Enable Media Replace
* Loco Translate
* Regenerate Thumbnails
* WP Crontrol
* WP Debugging
* WP-Sweep

**Comment by bugsysop** [comment]
Can't reproduce the bug this morning (here it's morning!) with various configs of other plugins... I think this is because there is _no_ translation package update.

**Comment by afragen** [comment]
Very strange error. Fortunately it's transient, unfortunately it's not reproducible.

I'm not certain this is directly related to Git Updater, but if it can be reliably reproduced I'll certainly look into it.

Please reopen this issue if you need to.

**Comment by bugsysop** [comment]
Thanks !
